# Generated by Django 5.2.8 on 2025-12-19 03:43

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='email_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='provider_id_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_domain',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='email',
            field=core.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_id',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.fields.EncryptedEmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'provider_id_hash')},
        ),
        migrations.AlterModelTable(
            name='socialaccount',
            table='social_account',
        ),
    ]
