# Generated by Django 5.2.8 on 2026-01-01 03:41

import all_app.calendar_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.CharField(default=all_app.calendar_app.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Calendar', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(default=all_app.calendar_app.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(db_column='calendar_id', on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar')),
            ],
            options={
                'db_table': 'Event',
                'ordering': ['start_at'],
            },
        ),
    ]
