# Generated by Django 5.2.8 on 2025-12-25 08:07

import all_app.to_do_list.to_do_list_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('todolist_id', models.CharField(default=all_app.to_do_list.to_do_list_models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ToDoList',
            },
        ),
        migrations.CreateModel(
            name='ToDoListGroup',
            fields=[
                ('group_id', models.CharField(default=all_app.to_do_list.to_do_list_models.generate_group_id, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('todolist', models.ForeignKey(db_column='todolist_id', on_delete=django.db.models.deletion.CASCADE, to='to_do_list.todolist')),
            ],
            options={
                'db_table': 'ToDoListGroup',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='to_do_list.todolistgroup')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
