# Generated by Django 5.2.8 on 2026-01-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('to_do_list', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='todolistgroup',
            name='todolist',
            field=models.ForeignKey(db_column='todolist_id', on_delete=django.db.models.deletion.CASCADE, to='to_do_list.todolist'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='to_do_list.todolistgroup'),
        ),
    ]
