# Generated by Django 5.2.8 on 2026-01-01 03:37

import all_app.flashcards.flashcards_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.CharField(default=all_app.flashcards.flashcards_models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Flashcard',
            },
        ),
        migrations.CreateModel(
            name='FlashcardItem',
            fields=[
                ('card_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('learned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'FlashcardItem',
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('progress_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('last_reviewed', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FlashcardProgress',
            },
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('set_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'FlashcardSet',
            },
        ),
    ]
