# Generated by Django 5.2.8 on 2026-01-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='card',
            field=models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcarditem'),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='flashcard',
            field=models.ForeignKey(db_column='flashcard_id', on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcarditem',
            name='set',
            field=models.ForeignKey(db_column='set_id', on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcardset'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardprogress',
            unique_together={('card', 'user')},
        ),
    ]
