# Generated by Django 5.2.8 on 2026-01-01 03:37

import all_app.pomodoro.pomodoro_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('pomodoro_id', models.CharField(default=all_app.pomodoro.pomodoro_models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Pomodoro', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='stopped', max_length=10)),
                ('work_duration', models.IntegerField(default=25)),
                ('break_duration', models.IntegerField(default=5)),
                ('current_session', models.CharField(default='work', max_length=10)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Pomodoro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroHistory',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('study_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='running', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PomodoroHistory',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_work_duration', models.IntegerField(default=25)),
                ('default_break_duration', models.IntegerField(default=5)),
                ('auto_start_break', models.BooleanField(default=True)),
                ('enable_sounds', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PomodoroSettings',
            },
        ),
    ]
