# Generated by Django 5.2.8 on 2025-12-11 06:54

import all_app.pomodoro.pomodoro_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroHistory',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('study_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('interrupted', 'interrupted')], default='completed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PomodoroHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('pomodoro_id', models.CharField(default=all_app.pomodoro.pomodoro_models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Default Pomodoro', max_length=255)),
                ('status', models.CharField(choices=[('running', 'running'), ('paused', 'paused'), ('stopped', 'stopped'), ('completed', 'completed')], default='stopped', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Pomodoro',
            },
        ),
    ]
