# Generated by Django 5.2.8 on 2026-01-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pomodoro', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='pomodorohistory',
            name='pomodoro',
            field=models.ForeignKey(blank=True, db_column='pomodoro_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pomodoro.pomodoro'),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
