# Generated by Django 5.2.8 on 2026-01-01 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict, help_text='Cấu hình vị trí các widget')),
                ('show_pomodoro', models.BooleanField(default=True)),
                ('show_todo', models.BooleanField(default=True)),
                ('show_calendar', models.BooleanField(default=True)),
                ('show_habits', models.BooleanField(default=True)),
                ('show_flashcards', models.BooleanField(default=True)),
                ('show_productivity', models.BooleanField(default=True)),
                ('widget_order', models.JSONField(default=list, help_text='Thứ tự các widget')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System)')], default='light', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('pomodoro_start', 'Bắt đầu Pomodoro'), ('pomodoro_complete', 'Hoàn thành Pomodoro'), ('task_create', 'Tạo task mới'), ('task_complete', 'Hoàn thành task'), ('habit_complete', 'Hoàn thành thói quen'), ('flashcard_review', 'Ôn tập flashcard'), ('event_create', 'Tạo sự kiện'), ('login', 'Đăng nhập'), ('settings_update', 'Cập nhật cài đặt')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pomodoro_sessions', models.IntegerField(default=0)),
                ('pomodoro_minutes', models.IntegerField(default=0)),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('habits_completed', models.IntegerField(default=0)),
                ('habits_total', models.IntegerField(default=0)),
                ('flashcards_reviewed', models.IntegerField(default=0)),
                ('productivity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
