# Generated by Django 5.2.8 on 2025-12-11 06:54

import all_app.habit.habit_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitList',
            fields=[
                ('habitlist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_target', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'HabitList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitListLog',
            fields=[
                ('log_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(default='not_completed', max_length=32)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'HabitListLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.CharField(default=all_app.habit.habit_models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Habit',
            },
        ),
    ]
