# Generated by Django 5.2.8 on 2026-01-01 03:41

import all_app.habit.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pomodoro', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.CharField(default=all_app.habit.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Habit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitList',
            fields=[
                ('habitlist_id', models.CharField(default=all_app.habit.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_target', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(db_column='habit_id', on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
            ],
            options={
                'db_table': 'HabitList',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitListLog',
            fields=[
                ('log_id', models.CharField(default=all_app.habit.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('skipped', 'Skipped')], default='not_completed', max_length=32)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('habitlist', models.ForeignKey(db_column='habitlist_id', on_delete=django.db.models.deletion.CASCADE, to='habit.habitlist')),
                ('pomodoro_history', models.ForeignKey(blank=True, db_column='pomodoro_history_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pomodoro.pomodorohistory')),
            ],
            options={
                'db_table': 'HabitListLog',
                'ordering': ['-date'],
                'unique_together': {('habitlist', 'date')},
            },
        ),
    ]
